import core.test.test_game_control
import core.test.test_event
import core.test.test_frames
import core.test.test_players_control
import ext.test.test_game_init
import ext.test.test_card_pool
import ext.test.test_player
import ext.test.test_players_control
import ext.test.test_slash
import ext.test.test_peach
import ext.test.test_arson_attack
import ext.test.test_duel
import ext.test.test_dragon_heart_martial_saint_slash_response
import ext.test.test_dragon_heart
import ext.test.test_martial_saint
import ext.test.test_zhangba_serpent_spear
import ext.test.test_vermilion_feather_fan
import ext.test.test_sabotage
import ext.test.test_no_onhand_region_if_no_cards
import ext.test.test_arson_attack_to_player_with_equipment_only
import ext.test.test_distance_horses
import ext.test.test_steal
import ext.test.test_rattan_armor
import ext.test.test_merciless
import ext.test.test_intellect_gathering
import ext.test.test_heavenly_scent
import ext.test.test_surprise_raid
import ext.test.test_fury_pith
import ext.test.test_brink_of_death_and_rescue
import ext.test.test_suicide
import ext.test.test_bequeathed_strategy
import ext.test.test_youth_beauty
print 'Kernal test finished.'
import gateway.wsgi.test
print 'Test finished.'
